<?php 
	get_header(); 
?>
<?php 
	get_template_part('template-parts/background');
?>
<?php 
	get_template_part('template-parts/aside-btn');
?>
<?php 
	get_template_part('template-parts/latest-ai');
?>
<?php 
	get_template_part('template-parts/latest-coding');
?>
<?php 
	get_template_part('template-parts/to-top');
?>
<?php
	get_footer(); 
?>